"""
Django settings for content_aggregator project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

from django.core.management.utils import get_random_secret_key

from dotenv import load_dotenv


# Load environment variables from a .env file
load_dotenv()

# Celery settings

# Redis URL with SSL options embedded
# So setting the ssl_cert_reqs in query string worked for heroku development
redis_url = os.getenv("REDIS_URL", 'redis://localhost:6379')

# Append SSL certificate reqs
CELERY_BROKER_URL = f"{redis_url}?ssl_cert_reqs=CERT_NONE"
CELERY_RESULT_BACKEND = f"{redis_url}?ssl_cert_reqs=CERT_NONE"

# Celery Beat Schedule - Production optimized timing
# Content is refreshed at different intervals to avoid recycling too often
CELERY_BEAT_SCHEDULE = {
    # High-traffic categories: every 4 hours
    'fetch-general-content': {
        'task': 'blog.tasks.fetch_general_content',
        'schedule': 4 * 60 * 60,  # 4 hours
    },
    'fetch-ai-content': {
        'task': 'blog.tasks.fetch_ai_content',
        'schedule': 4 * 60 * 60,  # 4 hours
    },
    'fetch-crypto-content': {
        'task': 'blog.tasks.fetch_crypto_content',
        'schedule': 4 * 60 * 60,  # 4 hours (fast-moving market)
    },
    # Medium-traffic categories: every 6 hours
    'fetch-cyber-content': {
        'task': 'blog.tasks.fetch_cyber_content',
        'schedule': 6 * 60 * 60,  # 6 hours
    },
    'fetch-software-development': {
        'task': 'blog.tasks.fetch_sd_content',
        'schedule': 6 * 60 * 60,  # 6 hours
    },
    'fetch-mobile-pc-content': {
        'task': 'blog.tasks.fetch_mobile_pc_content',
        'schedule': 6 * 60 * 60,  # 6 hours
    },
    'fetch-medical-news': {
        'task': 'blog.tasks.fetch_medical_news',
        'schedule': 6 * 60 * 60,  # 6 hours
    },
    # Lower-traffic categories: every 8 hours
    'fetch-python-content': {
        'task': 'blog.tasks.fetch_python_content',
        'schedule': 8 * 60 * 60,  # 8 hours
    },
    'fetch-ui-ux-content': {
        'task': 'blog.tasks.fetch_ui_ux_content',
        'schedule': 8 * 60 * 60,  # 8 hours
    },
    'fetch-ai-medical-imaging': {
        'task': 'blog.tasks.fetch_ai_medical_imaging',
        'schedule': 8 * 60 * 60,  # 8 hours
    },
    # Slow-moving categories: every 12 hours
    'fetch-tech-jobs': {
        'task': 'blog.tasks.fetch_tech_jobs',
        'schedule': 12 * 60 * 60,  # 12 hours
    },
}

# Adding SSL configuration
# Setting ssl_cert_reqs as a dictionary format in transport options here didn't work which is interesting
# CELERY_BROKER_URL = os.environ.get('REDIS_TLS_URL', 'redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = os.environ.get('REDIS_TLS_URL', 'redis://localhost:6379/0')
# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     'visibility_timeout': 3600,
#     'ssl': {
#         'ssl_cert_reqs': ssl.CERT_NONE  # or CERT_REQUIRED, CERT_OPTIONAL depending on your security needs
#     }
# }


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My apps
    "blog.apps.BlogConfig",
    "forum.apps.ForumConfig",
    "user_creation.apps.UserCreationConfig",
    "medical_imaging.apps.MedicalImagingConfig",
    "personal_blog.apps.PersonalBlogConfig",
    "stories.apps.StoriesConfig",

    # Third-Party Apps
    'django_celery_beat',
    "django_apscheduler",
    "reset_migrations",
    "crispy_forms",
    'bootstrap4',
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'content_aggregator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'forum.context_processors.get_recent_posts',
            ],
        },
    },
]

WSGI_APPLICATION = 'content_aggregator.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

if DEVELOPMENT_MODE is True:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
    }
# elif len(sys.argv) > 0 and sys.argv[1] != 'collectstatic':
#     if os.getenv("DATABASE_URL", None) is None:
#         raise Exception("DATABASE_URL environment variable not defined")
#     DATABASES = {
#         "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
#     }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)


# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CKEditor settings
CKEDITOR_UPLOAD_PATH = 'upload/'
CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor/"

# CKEditor configuration
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 400,
        'width': '100%',
        'extraPlugins': ','.join([
            'codesnippet',
            'uploadimage',
        ]),
        'codeSnippet_theme': 'monokai_sublime',
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('MY_EMAIL')
EMAIL_HOST_PASSWORD = os.environ.get('MY_PASSWORD')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_URL = '/user/login/'
LOGIN_REDIRECT_URL = '/home/'
