# Generated by Django 4.2.4 on 2026-01-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_rssfeed_alter_cryptocontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImagingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('link', models.URLField(max_length=2000)),
                ('content_name', models.CharField(max_length=100)),
                ('guid', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=2000, null=True)),
                ('source_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed')),
            ],
            options={
                'verbose_name': 'Medical Imaging Content',
                'verbose_name_plural': 'Medical Imaging Contents',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalImagingArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Brief summary for previews', max_length=500)),
                ('body', models.TextField(help_text='Article content (supports HTML from CKEditor)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='medical_imaging/featured/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('primary_topic', models.CharField(choices=[('fairness', 'Fairness & Equity'), ('bias', 'Bias Detection'), ('ethics', 'Ethics'), ('regulation', 'Regulation & Policy'), ('clinical', 'Clinical Applications'), ('research', 'Research'), ('tutorial', 'Tutorial'), ('news', 'Industry News')], max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Imaging Article',
                'verbose_name_plural': 'Medical Imaging Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medical_imaging/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility text', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medical_imaging.medicalimagingarticle')),
            ],
            options={
                'verbose_name': 'Article Image',
                'verbose_name_plural': 'Article Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='medical_imaging.medicalimagingarticle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
