# Generated by Django 4.2.4 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalimagingarticle',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicalimagingarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalimagingarticle',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='medicalimagingarticle',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
