# Generated by Django 4.2.4 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.TextField(max_length=1000),
        ),
    ]
