# Generated by Django 4.2.4 on 2026-01-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('category', models.CharField(choices=[('general', 'General Tech'), ('python', 'Python'), ('cybersecurity', 'Cyber Security'), ('software_dev', 'Software Development'), ('ui_ux', 'UI/UX'), ('mobile_pc', 'Mobile & PC'), ('jobs', 'Job Updates'), ('crypto', 'Crypto'), ('medical_imaging', 'AI & Medical Imaging')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('fetch_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cryptocontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='cybersecuritycontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='generalcontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='jobupdatescontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='mobilepccontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='pythoncontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='softwaredevelopmentcontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='uiuxcontent',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='cryptocontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='cybersecuritycontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='generalcontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='jobupdatescontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='mobilepccontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='pythoncontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='softwaredevelopmentcontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.AddField(
            model_name='uiuxcontent',
            name='source_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed'),
        ),
        migrations.CreateModel(
            name='UserBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
