# Generated by Django 4.2.4 on 2026-01-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rssfeed_alter_cryptocontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='category',
            field=models.CharField(choices=[('general', 'General Tech'), ('python', 'Python'), ('cybersecurity', 'Cyber Security'), ('software_dev', 'Software Development'), ('ui_ux', 'UI/UX'), ('mobile_pc', 'Mobile & PC'), ('jobs', 'Job Updates'), ('crypto', 'Crypto'), ('medical_news', 'Medical News'), ('ai_medical_imaging', 'AI in Medical Imaging')], max_length=50),
        ),
        migrations.CreateModel(
            name='MedicalNewsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('link', models.URLField(max_length=2000)),
                ('content_name', models.CharField(max_length=100)),
                ('guid', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=2000, null=True)),
                ('source_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed')),
            ],
            options={
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIMedicalImagingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('link', models.URLField(max_length=2000)),
                ('content_name', models.CharField(max_length=100)),
                ('guid', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=2000, null=True)),
                ('source_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.rssfeed')),
            ],
            options={
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
    ]
