# Generated by Django 4.2.4 on 2026-01-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_rssfeed_category_aicontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aimedicalimagingcontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cryptocontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cybersecuritycontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generalcontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobupdatescontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalnewscontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mobilepccontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pythoncontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='softwaredevelopmentcontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uiuxcontent',
            name='content_name',
            field=models.CharField(max_length=255),
        ),
    ]
