# Generated by Django 4.2.4 on 2026-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
